project_id = ""

[api]
  port = 54321
  schemas = ["public", "storage", "graphql_public"]
  extra_search_path = ["public", "extensions"]
  max_rows = 2000

[db]
  port = 54322
  major_version = 15

[studio]
  port = 54323

[inbucket]
  port = 54324

[storage]
  port = 54325

[pgmeta]
  port = 54326

[edge_runtime]
  port = 54327

